spring.application.name=guts-proxy
server.port=9090

proxy.target-url=http://localhost:8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.jackson.serialization.indent_output=true

security.master-key=${MASTER_KEY}

resilience4j.circuitbreaker.instances.iamService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.iamService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.iamService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.iamService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.iamService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.iamService.permittedNumberOfCallsInHalfOpenState=2
